In [1]:
import numpy as np

In [4]:
x = np.array([[0.8, 0.05, 0.05], [0.05, 0.75, 0.1], [0.05, 0.1, 0.75]])
print(x)
print(x.shape)

[[0.8  0.05 0.05]
 [0.05 0.75 0.1 ]
 [0.05 0.1  0.75]]
(3, 3)


In [5]:
print(np.linalg.inv(x))

[[ 1.25925926 -0.07407407 -0.07407407]
 [-0.07407407  1.36182336 -0.17663818]
 [-0.07407407 -0.17663818  1.36182336]]
